import { DetectedStack, StackDetector } from '../helpers/StackDetector';

/**
 * Shared, framework-agnostic builder for the Copilot instructions file.
 * Used by both GenerateInstructionsCommand and generateInstructionsTool.
 */
export function buildInstructionsContent(
    projectName: string,
    mode: 'featureFirst' | 'layerFirst',
    stack: DetectedStack | null,
    features: string[],
): string {
    const modeLabel = mode === 'featureFirst' ? 'Feature-First' : 'Layer-First';
    const lines: string[] = [];

    lines.push(`# Copilot Instructions — ${projectName}`);
    lines.push('');
    lines.push('> Auto-generated by **Dart Clean Architecture** extension.');
    lines.push('> Update this file whenever your stack or conventions change.');
    lines.push('');

    lines.push('## Scaffolding Tools (VS Code Extension)');
    lines.push('');
    lines.push('This project uses the **Dart Clean Architecture** VS Code extension.');
    lines.push('**ALWAYS use the extension Language Model Tools for any scaffolding operation.**');
    lines.push('NEVER create feature folders, use case files, or this instructions file manually.');
    lines.push('');
    lines.push('| Operation | Tool |');
    lines.push('|---|---|');
    lines.push('| Inspect architecture / list existing features | `#inspectArchitecture` |');
    lines.push('| Detect technology stack from pubspec.yaml | `#detectStack` |');
    lines.push('| Create a new feature (no CRUD) | `#createFeature` |');
    lines.push('| Create a feature with CRUD and typed entity | `#createFeatureCrud` |');
    lines.push('| Add a use case to an existing feature | `#createUseCase` |');
    lines.push('| Regenerate this AI instructions file | `#generateInstructions` |');
    lines.push('');
    lines.push('The tools handle file placement, barrel exports, and naming conventions automatically.');
    lines.push('');

    lines.push('## Project Overview');
    lines.push('');
    lines.push(`- **Language / Framework:** Dart / Flutter`);
    lines.push(`- **Architecture:** Clean Architecture (${modeLabel})`);
    lines.push(`- **Structure root:** \`lib/\``);
    lines.push('');

    lines.push('## Directory Structure');
    lines.push('');
    if (mode === 'featureFirst') {
        lines.push('Code is organised by **feature** (Feature-First):');
        lines.push('');
        lines.push('```');
        lines.push('lib/');
        lines.push('└── features/');
        lines.push('    └── <feature>/');
        lines.push('        ├── domain/          # Business logic — no external dependencies');
        lines.push('        │   ├── entities/    # Core business objects (pure Dart classes)');
        lines.push('        │   ├── usecases/    # One class per use case');
        lines.push('        │   └── repositories/ # Abstract contracts (interfaces)');
        lines.push('        ├── data/            # Infrastructure — implements domain contracts');
        lines.push('        │   ├── datasources/ # Remote/local data sources');
        lines.push('        │   │   ├── api/');
        lines.push('        │   │   ├── local/');
        lines.push('        │   │   └── remote/');
        lines.push('        │   ├── models/      # DTOs / serialisation classes');
        lines.push('        │   └── repositories/ # Repository implementations');
        lines.push('        └── ui/              # Presentation layer');
        lines.push('            ├── blocs/       # State management');
        lines.push('            ├── screens/     # Full pages');
        lines.push('            └── widgets/     # Reusable UI components');
        lines.push('```');
    } else {
        lines.push('Code is organised by **layer** (Layer-First):');
        lines.push('');
        lines.push('```');
        lines.push('lib/');
        lines.push('├── domain/              # All business logic — no external dependencies');
        lines.push('│   └── <feature>/');
        lines.push('│       ├── entities/');
        lines.push('│       ├── usecases/');
        lines.push('│       └── repositories/');
        lines.push('├── data/                # All infrastructure — implements domain contracts');
        lines.push('│   └── <feature>/');
        lines.push('│       ├── datasources/');
        lines.push('│       ├── models/');
        lines.push('│       └── repositories/');
        lines.push('└── ui/                  # All presentation');
        lines.push('    └── <feature>/');
        lines.push('        ├── blocs/');
        lines.push('        ├── screens/');
        lines.push('        └── widgets/');
        lines.push('```');
    }
    lines.push('');

    lines.push('## Technology Stack');
    lines.push('');
    const detector = new StackDetector();
    if (stack && !detector.isEmpty(stack)) {
        detector.format(stack).forEach(l => lines.push(`- ${l}`));
    } else {
        lines.push('_(Stack not detected — update this section manually)_');
    }
    lines.push('');

    if (stack) {
        const stateGuide = buildStateManagementGuidance(stack);
        if (stateGuide) { lines.push(stateGuide); }
        const diGuide = buildDIGuidance(stack);
        if (diGuide) { lines.push(diGuide); }
        const routingGuide = buildRoutingGuidance(stack);
        if (routingGuide) { lines.push(routingGuide); }
        const serializationGuide = buildSerializationGuidance(stack);
        if (serializationGuide) { lines.push(serializationGuide); }
    }

    lines.push('## Naming Conventions');
    lines.push('');
    lines.push('### Files — `snake_case`');
    lines.push('');
    lines.push('| Artifact | Pattern | Example |');
    lines.push('|---|---|---|');
    lines.push('| Entity | `<feature>.entity.dart` | `auth.entity.dart` |');
    lines.push('| Repository (abstract) | `<feature>.repository.dart` | `auth.repository.dart` |');
    lines.push('| Repository (impl) | `<feature>.repository_impl.dart` | `auth.repository_impl.dart` |');
    lines.push('| Datasource (abstract) | `<feature>.datasource.dart` | `auth.datasource.dart` |');
    lines.push('| Use case | `<action>_<feature>.usecase.dart` | `login_auth.usecase.dart` |');
    lines.push('| Model / DTO | `<feature>.model.dart` | `auth.model.dart` |');
    lines.push('| Barrel / index | `index.dart` | `index.dart` |');
    lines.push('');
    lines.push('### Classes — `PascalCase`');
    lines.push('');
    lines.push('```dart');
    lines.push('class AuthEntity         { ... }   // Entity');
    lines.push('abstract class AuthRepository { ... }   // Repository contract');
    lines.push('class AuthRepositoryImpl implements AuthRepository { ... }');
    lines.push('abstract class AuthDatasource { ... }   // Datasource contract');
    lines.push('class LoginAuthUseCase    { ... }   // Use case');
    lines.push('class AuthModel           { ... }   // DTO');
    lines.push('```');
    lines.push('');

    lines.push('## Clean Architecture Rules');
    lines.push('');
    lines.push('### Layer Dependency Direction');
    lines.push('');
    lines.push('```');
    lines.push('UI  →  Domain  ←  Data');
    lines.push('```');
    lines.push('');
    lines.push('- **Domain** has **zero** external package dependencies (pure Dart).');
    lines.push('- **Data** depends on Domain (implements repository/datasource contracts).');
    lines.push('- **UI** depends on Domain (uses use cases and entities).');
    lines.push('- **Data ↔ UI** must **never** import each other directly.');
    lines.push('');
    lines.push('### Use Cases');
    lines.push('');
    lines.push('- One use case per file, one responsibility per use case.');
    lines.push('- Always injected via constructor: `const LoginUseCase(this._repository);`');
    lines.push('- Called via `call()` method: `final result = await loginUseCase();`');
    lines.push('');
    lines.push('### Repositories');
    lines.push('');
    lines.push('- Contract (abstract class) lives in **domain/repositories/**.');
    lines.push('- Implementation lives in **data/repositories/**.');
    lines.push('- Never instantiate the implementation directly in UI or domain — use DI.');
    lines.push('');
    lines.push('### Entities');
    lines.push('');
    lines.push('- Pure Dart classes — no JSON serialisation logic.');
    lines.push('- Prefer `const` constructors and immutable fields.');
    lines.push('- Serialisation / mapping lives in the **model** (data layer).');
    lines.push('');

    if (features.length > 0) {
        lines.push('## Existing Features');
        lines.push('');
        lines.push('The following features already exist in this project:');
        lines.push('');
        features.forEach(f => lines.push(`- \`${f}\``));
        lines.push('');
        lines.push('When adding code to an existing feature, follow its existing conventions.');
        lines.push('When creating a new feature, follow the structure outlined above.');
        lines.push('');
    }

    lines.push('## Guidance for AI Code Generation');
    lines.push('');
    lines.push('When generating or modifying code in this project:');
    lines.push('');
    lines.push('0. **Always scaffold with extension tools** — to create features, use cases, or');
    lines.push('   regenerate this file, call the `#inspectArchitecture`, `#createFeature`,');
    lines.push('   `#createFeatureCrud`, `#createUseCase`, or `#generateInstructions` tools.');
    lines.push('   Never create boilerplate files from scratch manually.');
    lines.push('1. **Respect layer boundaries** — do not import data/ classes from domain/,');
    lines.push('   and do not import data/ or ui/ from domain/.');
    lines.push(`2. **Follow ${modeLabel} structure** — place new features in the correct root.`);
    lines.push('3. **Constructor injection** — never use service locators directly inside');
    lines.push('   domain classes; receive dependencies via constructor.');
    lines.push('4. **Repository-first** — define the abstract contract in domain before');
    lines.push('   writing the data-layer implementation.');
    lines.push('5. **Barrel exports** — every layer subdirectory has an `index.dart`; export');
    lines.push('   public symbols from there instead of importing internal paths.');
    lines.push('6. **One file, one class** — avoid putting multiple top-level classes in one');
    lines.push('   file (except for closely related value objects).');
    lines.push('7. **Immutable entities** — prefer `const` constructors and `final` fields');
    lines.push('   in domain entities.');
    lines.push('8. **Named parameters** — use named parameters in constructors when there');
    lines.push('   are two or more parameters.');
    lines.push('');

    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Stack-specific guidance blocks (shared)
// ---------------------------------------------------------------------------

function buildStateManagementGuidance(stack: DetectedStack): string | null {
    const sm = stack.stateManagement;
    if (sm.length === 0) { return null; }
    const lines: string[] = [];

    if (sm.includes('flutter_bloc') || sm.includes('bloc')) {
        lines.push('## State Management — flutter_bloc');
        lines.push('');
        lines.push('- BLoC and Cubit files live in `ui/blocs/<feature>/`.');
        lines.push('- Use `Cubit` for simple states, `Bloc` for event-driven flows.');
        lines.push('- Define named state classes (`AuthInitial`, `AuthLoading`, `AuthSuccess`, `AuthFailure`).');
        lines.push('- Never call business logic directly inside widgets — go through a Cubit/Bloc.');
        lines.push('- Use `BlocProvider` at the appropriate widget-tree level (route or subtree).');
        lines.push('');
    } else if (sm.includes('flutter_riverpod') || sm.includes('riverpod')) {
        lines.push('## State Management — Riverpod');
        lines.push('');
        lines.push('- Providers live in `ui/blocs/<feature>/` or a top-level `providers/` folder.');
        lines.push('- Prefer `AsyncNotifierProvider` for async state, `NotifierProvider` for sync.');
        lines.push('- Keep providers small and composable.');
        lines.push('- Annotate providers with `@riverpod` when using code generation.');
        lines.push('');
    } else if (sm.includes('provider')) {
        lines.push('## State Management — Provider');
        lines.push('');
        lines.push('- `ChangeNotifier` classes live in `ui/blocs/<feature>/`.');
        lines.push('- Register providers in your `MultiProvider` at the app root.');
        lines.push('');
    }

    return lines.length > 0 ? lines.join('\n') : null;
}

function buildDIGuidance(stack: DetectedStack): string | null {
    const di = stack.dependencyInjection;
    if (di.length === 0) { return null; }
    const lines: string[] = [];

    if (di.includes('get_it') || di.includes('injectable')) {
        lines.push('## Dependency Injection — GetIt');
        lines.push('');
        lines.push('- Register dependencies in a dedicated `injection.dart` (or `di/`) file.');
        lines.push('- Use factories for use cases, singletons for repositories and datasources.');
        if (di.includes('injectable')) {
            lines.push('- Annotate classes with `@injectable`, `@singleton`, or `@lazySingleton`.');
            lines.push('- Run `dart run build_runner build` after adding new annotated classes.');
        }
        lines.push('- Never call `GetIt.instance.get<T>()` inside domain classes.');
        lines.push('');
    }

    return lines.length > 0 ? lines.join('\n') : null;
}

function buildRoutingGuidance(stack: DetectedStack): string | null {
    const routing = stack.routing;
    if (routing.length === 0) { return null; }
    const lines: string[] = [];

    if (routing.includes('go_router')) {
        lines.push('## Routing — GoRouter');
        lines.push('');
        lines.push('- Define routes in a central `router.dart` file.');
        lines.push('- Use named routes (`GoRoute(name: ...)`) for type-safe navigation.');
        lines.push('- Screens receive their route parameters from `GoRouterState`, not from constructors.');
        lines.push('');
    } else if (routing.includes('auto_route')) {
        lines.push('## Routing — AutoRoute');
        lines.push('');
        lines.push('- Annotate screens with `@RoutePage()`.');
        lines.push('- Run `dart run build_runner build` after adding new routes.');
        lines.push('');
    }

    return lines.length > 0 ? lines.join('\n') : null;
}

function buildSerializationGuidance(stack: DetectedStack): string | null {
    const ser = stack.serialization;
    if (ser.length === 0) { return null; }
    const lines: string[] = [];

    if (ser.includes('freezed') || ser.includes('freezed_annotation')) {
        lines.push('## Models / Serialisation — Freezed');
        lines.push('');
        lines.push('- Annotate model classes with `@freezed`.');
        lines.push('- Run `dart run build_runner build` after modifying model classes.');
        lines.push('- Keep the generated `.freezed.dart` and `.g.dart` files — do not edit them manually.');
        lines.push('- Data models (DTOs) live in `data/models/`; domain entities in `domain/entities/`.');
        lines.push('');
    } else if (ser.includes('json_serializable') || ser.includes('json_annotation')) {
        lines.push('## Models / Serialisation — json_serializable');
        lines.push('');
        lines.push('- Annotate model classes with `@JsonSerializable()`.');
        lines.push('- Run `dart run build_runner build` after modifying model classes.');
        lines.push('- Add `fromJson` factory and `toJson` method to each model.');
        lines.push('');
    }

    return lines.length > 0 ? lines.join('\n') : null;
}
