import { StringTransformer } from '../utils/StringTransformer';

export interface EntityConfig {
  entityName: string;
  identifierField: string;
  identifierType: string;
  additionalFields?: Array<{ name: string; type: string }>;
}

// ─────────────────────────────────────────────────────────────────────────────
// TemplateGenerator
//
// Produces Dart source code for every artifact generated by the extension.
// All output follows:
//   • Effective Dart Style (dart.dev/effective-dart/style)
//   • sort_constructors_first member ordering (very_good_analysis)
//   • Immutability-first (const constructors, final fields)
//   • Constructor injection for all dependencies
// ─────────────────────────────────────────────────────────────────────────────

export class TemplateGenerator {

  // ── Index / barrel files ──────────────────────────────────────────────────

  generateDataIndexContent(
    featureName: string,
    projectName: string,
  ): string {
    const exports = [
      `export 'package:${projectName}/features/${featureName}/data/models/index.dart';`,
      `export 'package:${projectName}/features/${featureName}/data/repositories/${featureName}.repository_impl.dart';`,
    ];

    return exports.join('\n');
  }

  generateDomainIndexContent(
    featureName: string,
    projectName: string,
    includeEntities = false,
  ): string {
    const exports = [
      `export 'package:${projectName}/features/${featureName}/domain/usecases/index.dart';`,
      `export 'package:${projectName}/features/${featureName}/domain/repositories/${featureName}.repository.dart';`,
    ];

    if (includeEntities) {
      exports.unshift(
        `export 'package:${projectName}/features/${featureName}/domain/entities/index.dart';`,
      );
    }

    return exports.join('\n');
  }

  /** Barrel for the entities sub-directory using the entity file name. */
  generateEntitiesIndexContentForEntity(
    featureName: string,
    projectName: string,
    entityFileName: string,
  ): string {
    return `export 'package:${projectName}/features/${featureName}/domain/entities/${entityFileName}.entity.dart';`;
  }

  generateUiIndexContent(featureName: string, projectName: string): string {
    return [
      `export 'package:${projectName}/features/${featureName}/ui/blocs/index.dart';`,
      `export 'package:${projectName}/features/${featureName}/ui/screens/index.dart';`,
      `export 'package:${projectName}/features/${featureName}/ui/widgets/index.dart';`,
    ].join('\n');
  }

  generateMainFeatureIndexContent(featureName: string, projectName: string): string {
    return [
      `export 'package:${projectName}/features/${featureName}/data/index.dart';`,
      `export 'package:${projectName}/features/${featureName}/domain/index.dart';`,
      `export 'package:${projectName}/features/${featureName}/ui/index.dart';`,
    ].join('\n');
  }

  /** Barrel for the entities sub-directory. Empty unless CRUD scaffolding is requested. */
  generateEntitiesIndexContent(
    featureName: string,
    projectName: string,
    includeEntity = false,
  ): string {
    if (!includeEntity) {
      return '';
    }

    return `export 'package:${projectName}/features/${featureName}/domain/entities/${featureName}.entity.dart';`;
  }

  /** Barrel for the datasources sub-directory. Empty unless CRUD scaffolding is requested. */
  generateDatasourcesIndexContent(
    featureName: string,
    projectName: string,
    includeDatasource = false,
  ): string {
    if (!includeDatasource) {
      return '';
    }

    return `export 'package:${projectName}/features/${featureName}/data/datasources/${featureName}.datasource.dart';`;
  }

  generateUseCaseIndexContent(
    featureName: string,
    projectName: string,
    useCaseFiles: string[],
  ): string {
    return useCaseFiles
      .map(file => `export 'package:${projectName}/features/${featureName}/domain/usecases/${file}';`)
      .join('\n');
  }

  // ── Entity ────────────────────────────────────────────────────────────────

  /**
   * Generates the domain entity class.
   *
   * Template conventions (Effective Dart):
   *   • `const` constructor listed first (sort_constructors_first)
   *   • `final` fields (immutability)
   *   • `copyWith`, `==`, `hashCode`, `toString` in that order
   *   • No serialisation logic — that belongs in the data layer model
   */
  generateEntityContent(entityConfig: EntityConfig): string {
    const entityClassName = `${entityConfig.entityName}Entity`;
    const allFields = [
      { name: entityConfig.identifierField, type: entityConfig.identifierType },
      ...(entityConfig.additionalFields || []),
    ];

    const constructorParams = allFields
      .map(f => `    required this.${f.name},`)
      .join('\n');

    const fieldDeclarations = allFields
      .map(f => `  final ${f.type} ${f.name};`)
      .join('\n');

    const copyWithParams = allFields
      .map(f => `    ${f.type}? ${f.name},`)
      .join('\n');

    const copyWithArgs = allFields
      .map(f => `      ${f.name}: ${f.name} ?? this.${f.name},`)
      .join('\n');

    const equalityChecks = allFields
      .map(f => `          ${f.name} == other.${f.name}`)
      .join(' &&\n');

    const hashParts = allFields.map(f => `${f.name}.hashCode`);
    const hashExpr = hashParts.length === 1
      ? hashParts[0]
      : hashParts.join(' ^ ');

    const toStringFields = allFields
      .map(f => `${f.name}: \$${f.name}`)
      .join(', ');

    return `/// Domain entity: ${entityConfig.entityName}.
///
/// Pure Dart class — no serialisation logic, no external dependencies.
class ${entityClassName} {
  const ${entityClassName}({
${constructorParams}
  });

${fieldDeclarations}

  /// Returns a copy of this entity with the provided fields replaced.
  ${entityClassName} copyWith({
${copyWithParams}
  }) {
    return ${entityClassName}(
${copyWithArgs}
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ${entityClassName} &&
          runtimeType == other.runtimeType &&
${equalityChecks};

  @override
  int get hashCode => ${hashExpr};

  @override
  String toString() => '${entityClassName}(${toStringFields})';
}`;
  }

  // ── Datasource ────────────────────────────────────────────────────────────

  /**
   * Abstract datasource contract.
   *
   * Lives in `data/datasources/` and declares the operations that concrete
   * sources (API, local DB, cache) must fulfil.
   * Keep method signatures aligned with the companion `${className}Repository`.
   */
  generateDatasourceContent(className: string): string {
    return `/// Abstract contract for [${className}] data sources.
///
/// Implement once per concrete source (e.g. REST API, local database, cache).
/// Keep method signatures aligned with [${className}Repository].
abstract class ${className}Datasource {
  // TODO: declare operations mirroring the repository contract.
  // Prefer typed signatures. Examples:
  //
  //   Future<${className}Model> fetchById(String id);
  //   Future<List<${className}Model>> fetchAll();
  //   Future<${className}Model> create(${className}Model model);
  //   Future<${className}Model> update(${className}Model model);
  //   Future<void> deleteById(String id);
}`;
  }

  /**
   * Concrete API (HTTP/REST) datasource skeleton.
   *
   * Inject the HTTP client via the constructor; never hard-code it.
   */
  generateApiDatasourceContent(
    className: string,
    featureName: string,
    projectName: string,
  ): string {
    return `import 'package:${projectName}/features/${featureName}/data/datasources/${featureName}.datasource.dart';

/// HTTP / REST implementation of [${className}Datasource].
///
/// Inject your HTTP client (e.g. Dio, http package) via the constructor
/// and register this class in your DI setup.
class ${className}ApiDatasource implements ${className}Datasource {
  const ${className}ApiDatasource(
    // TODO: add HTTP client parameter, e.g.: this._client,
  );

  // final Dio _client;

  // TODO: implement the operations declared in [${className}Datasource].
}`;
  }

  // ── Repository — abstract contract (CRUD) ─────────────────────────────────

  /**
   * Abstract repository with the four standard CRUD method signatures.
   *
   * Uses `${className}Entity` as the return / parameter type so callers
   * benefit from type-safety immediately; update signatures as your domain
   * requires.
   */
  generateRepositoryContent(className: string, featureName: string, projectName: string, entityConfig: EntityConfig): string {
    const entityClass = `${entityConfig.entityName}Entity`;
    const idField = entityConfig.identifierField;
    const idType = entityConfig.identifierType;
    const entityFileName = StringTransformer.transformInput(entityConfig.entityName);

    return `import 'package:${projectName}/features/${featureName}/domain/entities/${entityFileName}.entity.dart';

/// Abstract repository contract for the ${featureName} feature.
///
/// Belongs to the **domain layer** — no external package dependencies.
/// The implementation lives in
/// \`data/repositories/${featureName}.repository_impl.dart\`.
abstract class ${className}Repository {
  /// Persists a new [${entityClass}] and returns the saved result.
  Future<${entityClass}> create(${entityClass} entity);

  /// Returns the [${entityClass}] identified by [${idField}].
  Future<${entityClass}> read(${idType} ${idField});

  /// Replaces an existing [${entityClass}] and returns the updated result.
  Future<${entityClass}> update(${entityClass} entity);

  /// Permanently removes the [${entityClass}] identified by [${idField}].
  Future<void> delete(${idType} ${idField});
}`;
  }

  // ── Repository — abstract contract (blank, non-CRUD) ─────────────────────

  /**
   * Minimal abstract repository for features that do not need CRUD scaffolding.
   */
  generateBlankRepositoryContent(className: string, featureName: string): string {
    return `/// Abstract repository contract for the ${featureName} feature.
///
/// Belongs to the **domain layer** — no external package dependencies.
/// The implementation lives in
/// \`data/repositories/${featureName}.repository_impl.dart\`.
abstract class ${className}Repository {
  // TODO: define only the domain operations this feature actually needs.
}`;
  }

  // ── Repository — implementation (CRUD) ────────────────────────────────────

  generateRepositoryImplContent(
    className: string,
    featureName: string,
    projectName: string,
    entityConfig: EntityConfig,
  ): string {
    const entityClass = `${entityConfig.entityName}Entity`;
    const idField = entityConfig.identifierField;
    const idType = entityConfig.identifierType;

    return `import 'package:${projectName}/features/${featureName}/domain/index.dart';

/// Concrete implementation of [${className}Repository].
///
/// Register in your DI setup and bind to [${className}Repository].
class ${className}RepositoryImpl implements ${className}Repository {
  const ${className}RepositoryImpl();

  // TODO: inject your data source via constructor when ready.

  @override
  Future<${entityClass}> create(${entityClass} entity) async {
    // TODO: implement create.
    throw UnimplementedError('${className}RepositoryImpl.create');
  }

  @override
  Future<${entityClass}> read(${idType} ${idField}) async {
    // TODO: implement read.
    throw UnimplementedError('${className}RepositoryImpl.read');
  }

  @override
  Future<${entityClass}> update(${entityClass} entity) async {
    // TODO: implement update.
    throw UnimplementedError('${className}RepositoryImpl.update');
  }

  @override
  Future<void> delete(${idType} ${idField}) async {
    // TODO: implement delete.
    throw UnimplementedError('${className}RepositoryImpl.delete');
  }
}`;
  }

  // ── Repository — implementation (blank, non-CRUD) ─────────────────────────

  generateBlankRepositoryImplContent(
    className: string,
    featureName: string,
    projectName: string,
  ): string {
    return `import 'package:${projectName}/features/${featureName}/domain/index.dart';

/// Concrete implementation of [${className}Repository].
///
/// Add dependencies only when this feature actually needs external I/O
/// or integration points, then register the binding in your DI setup.
class ${className}RepositoryImpl implements ${className}Repository {
  const ${className}RepositoryImpl();

  // TODO: implement the methods declared in [${className}Repository].
}`;
  }

  // ── Use case ──────────────────────────────────────────────────────────────

  /**
   * Generates a single-responsibility use case class (standalone, no CRUD context).
   *
   * Used by CreateUseCaseCommand for adding individual use cases to features.
   */
  generateUseCaseContent(
    method: string,
    className: string,
    featureName: string,
    projectName: string,
  ): string {
    const methodCamelCase = StringTransformer.toCamelCase(method);
    const useCaseClassName = `${StringTransformer.toPascalCase(method)}UseCase`;

    return `import 'package:${projectName}/features/${featureName}/domain/repositories/${featureName}.repository.dart';

/// Use case: executes the [${methodCamelCase}] operation.
///
/// Delegates to [${className}Repository] and keeps the UI layer
/// decoupled from data-layer details.
class ${useCaseClassName} {
  const ${useCaseClassName}(this._repository);

  final ${className}Repository _repository;

  /// Executes the use case.
  ///
  /// Replace [Future<void>] with the actual return type and add
  /// the required parameters.
  Future<void> call() async {
    return _repository.${methodCamelCase}();
  }
}`;
  }

  /**
   * Generates a single-responsibility use case class.
   *
   * Conventions:
   *   • `const` constructor (sort_constructors_first)
   *   • Private `_repository` field
   *   • `call()` method — enables `await useCase()` Dart syntactic sugar
   *   • Return type is `Future<void>` as default placeholder;
   *     replace with the actual domain type.
   */
  generateCrudUseCaseContent(
    method: string,
    className: string,
    featureName: string,
    projectName: string,
    entityConfig: EntityConfig,
  ): string {
    const methodCamelCase = StringTransformer.toCamelCase(method);
    const useCaseClassName = `${StringTransformer.toPascalCase(method)}${entityConfig.entityName}UseCase`;
    const entityClass = `${entityConfig.entityName}Entity`;
    const idField = entityConfig.identifierField;
    const idType = entityConfig.identifierType;

    let callSignature: string;
    let callBody: string;

    switch (method) {
      case 'create':
        callSignature = `Future<${entityClass}> call(${entityClass} entity)`;
        callBody = `return _repository.create(entity);`;
        break;
      case 'read':
        callSignature = `Future<${entityClass}> call(${idType} ${idField})`;
        callBody = `return _repository.read(${idField});`;
        break;
      case 'update':
        callSignature = `Future<${entityClass}> call(${entityClass} entity)`;
        callBody = `return _repository.update(entity);`;
        break;
      case 'delete':
        callSignature = `Future<void> call(${idType} ${idField})`;
        callBody = `return _repository.delete(${idField});`;
        break;
      default:
        callSignature = `Future<void> call()`;
        callBody = `throw UnimplementedError('${useCaseClassName}.call');`;
    }

    const entityFileName = StringTransformer.transformInput(entityConfig.entityName);

    return `import 'package:${projectName}/features/${featureName}/domain/repositories/${featureName}.repository.dart';
import 'package:${projectName}/features/${featureName}/domain/entities/${entityFileName}.entity.dart';

/// Use case: executes the [${methodCamelCase}] operation on [${entityClass}].
///
/// Delegates to [${className}Repository] and keeps the UI layer
/// decoupled from data-layer details.
class ${useCaseClassName} {
  const ${useCaseClassName}(this._repository);

  final ${className}Repository _repository;

  /// Executes the use case.
  ${callSignature} async {
    ${callBody}
  }
}`;
  }

  // ── Single-method repository helpers (used by CreateUseCaseCommand) ────────

  /**
   * Creates an abstract repository with a single named method.
   * Used when adding a new use case to an existing feature.
   */
  generateRepositoryWithMethod(className: string, method: string): string {
    return `/// Abstract repository contract for the ${className} feature.
///
/// Domain layer — no external dependencies.
abstract class ${className}Repository {
  /// ${StringTransformer.toPascalCase(method)} operation.
  ///
  /// Replace [Future<void>] with the appropriate return type and
  /// add required parameters.
  Future<void> ${method}();
}`;
  }

  /**
   * Creates a repository implementation with a single named method.
   * Used when adding a new use case to a feature that has no repository yet.
   */
  generateRepositoryImplWithMethod(
    className: string,
    featureName: string,
    projectName: string,
    method: string,
  ): string {
    return `import 'package:${projectName}/features/${featureName}/domain/index.dart';

/// Concrete implementation of [${className}Repository].
class ${className}RepositoryImpl implements ${className}Repository {
  const ${className}RepositoryImpl();
  // TODO: inject datasource(s) and bind to [${className}Repository] in your DI setup.

  @override
  Future<void> ${method}() async {
    // TODO: implement ${method}.
    throw UnimplementedError('${className}RepositoryImpl.${method}');
  }
}`;
  }
}
