name: Deployment Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install --no-audit --no-fund --no-optional
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'