name: Deployment Pipeline

on:
  push:
    branches:
      - master
  release:
    types:
    - created
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install --no-audit --no-fund --omit=optional
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
    - name: Install vsce
      if: matrix.os == 'ubuntu-latest'
      run: npm install -g vsce
    - name: Login to VSCE
      if: matrix.os == 'ubuntu-latest'
      run: vsce login FlutterCleanArchitecture --pat ${{ secrets.YOUR_SECRET_NAME }}
    - name: Publish
      if: matrix.os == 'ubuntu-latest'
      run: npm run deploy
      env:
        YOUR_SECRET_NAME: ${{ secrets.YOUR_SECRET_NAME }}